spring:
  application:
    name: gateway
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  cloud:
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          - id: authorization-service
            uri: lb://authentication-service
            predicates:
              - Path=/authorization/**
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/users/**
          - id: ticket-service
            uri: lb://ticket-service
            predicates:
              - Path=/tickets/**
          - id: notification-service
            uri: lb://notification-service
            predicates:
              - Path=/notifications/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
#      need change?
      defaultZone: http://${USER_NAME}:${PASSWORD}@localhost:5002/eureka/

server:
  port: ${SERVER_PORT}

jwks:
    uri: ${JWKS_URI}