ACTIVE_PROFILE: dev
# in production, should use a secure way to store keys and passwords,
# such as environment variables or a secrets manager(AWS Secrets Manager).
PRIVATE_KEY: "private.key"
PUBLIC_KEY: "public.key"
POSTGRES_USERNAME: user
POSTGRES_PASSWORD: letmein
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DATABASE: localdb

USER_NAME: admin
PASSWORD: letmein

SERVER_PORT: 8080
UI_APP_URL: "http://localhost:3000"